var selectedFg = "#0177FF",
    selectedBg = "#FFF",
    bigBoxBorderColor = "#AAA",
    smallBoxBorderColor = "#E8E8E8",
    smallBoxBg = "#E8E8E8",
    ;

var titleStyle = [ "* {",
    "font-weight: bold;",
"}"
].join(" ");

var imageStyle = [ "* {",
    "border: none;",
    "font: 14px;",
"}"
].join(" ");

var generalStyle = [ "* {",
    "font-family: Helvetica, Verdana, sans-serif;", 
    "font-size:   10pt;",
    "font-weight: regular;",
    "color: rgb(68, 68, 68);",
    "background-color: " + selectedBg + ";",
    "selection-color: " + selectedFg + ";",
    "selection-background-color: " + selectedBg + ";", 
"}",
"*:disabled {",
  "color: " + bigBoxBorderColor + ";",
"}",
"QScrollBar:horizontal {",
 "border: 1px solid " + smallBoxBorderColor + ";",
 "border-radius: 4px;",
 "background: " + smallBoxBg + ";",
 "height: 10px;",
 "margin: 0px 0px 0px 0px;",
"}",
 "QScrollBar:vertical {",
    "border: 1px solid " + smallBoxBorderColor + ";",
"border-radius: 4px;",
    "background: " + smallBoxBg + ";",
"width: 10px;",
     "margin: 0px 0 0px 0;",
 "}",
 "QScrollBar::add-line:vertical {",
     "background: " + bigBoxBorderColor + ";",
     "height: 0px;",
     "subcontrol-position: bottom;",
     "subcontrol-origin: margin;",
 "}",
 "QScrollBar::add-line:horizontal {",
     "background: " + bigBoxBorderColor + ";",
     "width: 0px;",
     "subcontrol-position: bottom;",
     "subcontrol-origin: margin;",
 "}",
 "QScrollBar::sub-line:vertical {",
     "background: " + bigBoxBorderColor + ";",
     "height: 0px;",
     "subcontrol-position: top;",
     "subcontrol-origin: margin;",
 "}",
 "QScrollBar::sub-line:horizontal {",
     "background: " + bigBoxBorderColor + ";",
     "width: 0px;",
     "subcontrol-position: top;",
     "subcontrol-origin: margin;",
 "}",
"QScrollBar::down-arrow:vertical {",
     "width: 20px;",
     "height: 20px;",
"}",
"QScrollBar::up-arrow:vertical {",
     "width: 10px;",
     "height: 20px;",
"}", 
"QScrollBar::down-arrow:horizontal {",
     "width: 20px;",
     "height: 20px;",
     "background: " + selectedBg + ";",
"}",
"QScrollBar::up-arrow:horizontal {",
     "width: 10px;",
     "height: 20px;",
     "background: " + selectedBg + ";",
"}",
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {",
     "background: none;",
 "}",
"QScrollBar::handle {",
  "background-color: " + bigBoxBorderColor + ";",
  "border: 1px solid " + bigBoxBorderColor + ";",
 "border-radius: 4px;",
"}",
"QStatusBar {",
 //"background-color: rgb(1, 119, 255);",
"}",
"#desktopCollaborateLit, #desktopAccountingLit, #desktopManufactureLit, #_notice, #desktopPurchaseLit, #desktopSalesLit, #desktopSociallit {",
 "text-transform: lowercase;",
 "font-size: 18px;",
 "color: " + selectedFg + ";",
 "font-weight: 200;",
"}",
"QMenu {",
 "border-left: 1px solid " + bigBoxBorderColor + ";",
 "border-right: 1px solid " + bigBoxBorderColor + ";",
 "border-bottom: 1px solid " + bigBoxBorderColor + ";",
 "border-top: 1px solid " + bigBoxBorderColor + ";",
"}",
"QGroupBox {",
 "text-transform: uppercase;",
 "border-top: 1px solid " + smallBoxBorderColor + ";",
 "border-left: 1px solid qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #e8e8e8, stop: 0.05 #e8e8e8, stop: 0.06 #FFFFFF, stop: 1 #FFFFFF);",
"border-right: 1px solid qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #e8e8e8, stop: 0.05 #e8e8e8, stop: 0.06 #FFFFFF, stop: 1 #FFFFFF);",
 "margin-top: 1ex;",
"padding-top: 1ex;",
"}",
"QGroupBox::title {",
 "color: rgb(138, 138, 138);",
 "subcontrol-origin: margin;",
 "subcontrol-position: top center;",
 "padding: 0 3px;",
"}",
"QTabBar::tab:selected {",
"background-color: " + selectedBg + ";",
"color: " + selectedFg + ";",
 "border-bottom-color: " + selectedBg + ";",
"}",
"QTabBar::tab:!selected {",
"background-color: " + selectedBg + ";",
"color: #666;",
//"border-bottom-color: " + bigBoxBorderColor + ";",
//"border-top-color: " + selectedBg + ";",
// "border-left-color:" + selectedBg + ";",
//"border-right-color: " + selectedBg + ";",
//"border-radius: 0px;",
// "border-left: 1px solid qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #FFFFFF, stop: 0.8 #FFFFFF, stop: 0.9 #e8e8e8, stop: 1 #e8e8e8);",
//"border-right: 1px solid qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #FFFFFF, stop: 0.8 #FFFFFF, stop: 0.9 #e8e8e8, stop: 1 #e8e8e8);",
"}",
 "QTabBar::tab:disabled {",
"background-color: " + selectedBg + ";",
"color: " +  bigBoxBorderColor + ";",
 "border-bottom-color: " + bigBoxBorderColor + ";",
"}",
"QTabBar::tab {",
     "border: 1px solid " + bigBoxBorderColor + ";",
    "border-top-left-radius: 4px;",
    "border-top-right-radius: 4px;",
    "min-width: 8ex;",
    "padding-top: 2px;",
"padding-bottom: 2px;",
"padding-left: 4px;",
"padding-right: 4px;",
"}", 
"MenuButton::label {",
 "max-width: 90%;",
"}",
"VirtualClusterLineEdit QLabel {",
"background-color: none;",
"}",
"QTreeWidget  {",
  "selection-background-color: transparent;",
"}",
"QMenuBar::item:selected {",
  "background: " + selectedBg + ";",
  "selection-background-color:" + smallBoxBg + ";",
"}",
"QMenuBar::item:pressed {",
  "background: " + selectedBg + ";", 
"color: " + selectedFg + ";",
 "border-left: 1px solid " + bigBoxBorderColor + ";",
 "border-right: 1px solid " + bigBoxBorderColor + ";",
"}",
"QMenuBar::item:hover {",
"color: " + selectedFg + ";",
"}",
"QRadioButton::indicator {",
 "background-color: " + bigBoxBorderColor + ";",
 "width: 10px;",
    "height: 10px;",
"}",
"QRadioButton::indicator::unchecked {",
   "background-color: " + selectedBg + ";",
 "border: 2px solid " + bigBoxBorderColor + ";",
 "border-radius: 7px;",
"}",
"QRadioButton::indicator:unchecked:hover {",
       "background-color: " + selectedFg + ";",
  "border: 2px solid " + smallBoxBg + ";",  
"border-radius: 7px;",
"}",
"QRadioButton::indicator:unchecked:pressed {",
    "background-color: " + selectedFg + ";",
  "border: 2px solid " + smallBoxBg + ";",
 "border-radius: 7px;",
"}",
"QRadioButton::indicator::checked {",
   "background-color: " + selectedFg + ";",
  "border: 2px solid " + selectedBg + ";",
 "border-radius: 7px;",
"}",
"QRadioButton::indicator:checked:hover {",
  "background-color: " + selectedFg + ";",
  "border: 2px solid " + selectedBg + ";",
 "border-radius: 7px;",
"}",
"QRadioButton::indicator:checked:pressed {",
   "background-color: " + selectedFg + ";",
  "border: 2px solid " + selectedBg + ";",
 "border-radius: 7px;",
"}",


].join(" ");

var desktopMenuStyle = [ "* {",
    "selection-color: " + selectedFg + ";",
   "selection-background-color: " + selectedBg + ";",
//  "XTreeWidget::branch { border-image-source: none;};",
   "border-style: none;",
"}",

].join(" ");

try {
var app = QApplication;
app.setStyleSheet(generalStyle);
} catch(e) {
  QMessageBox.critical(mainwindow, "QApplication Error", e);
}